apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: bmpp
  namespace: deployments
spec:
  rules:
    - host: bullmoose-party.com
      http:
        paths:
          - backend:
              serviceName: bmpp
              servicePort: 8080
            path: /
    - host: www.bullmoose-party.com
      http:
        paths:
          - backend:
              serviceName: bmpp
              servicePort: 8080
  tls:
    - secretName: bullmoose-party.com
      hosts:
        - bullmoose-party.com
        - www.bullmoose-party.com
---
apiVersion: v1
kind: Service
metadata:
  name: bmpp
  namespace: deployments
spec:
  selector:
    app: bmpp
  ports:
    - name: bmpp
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmpp
  namespace: deployments
  labels:
    app: bmpp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmpp
  template:
    metadata:
      labels:
        app: bmpp
    spec:
      containers:
        - name: bmpp
          image: registry.paul-steele.com/bmpp:$BUILD_TAG
          ports:
            - name: bmpp
              containerPort: 8080
      imagePullSecrets:
        - name: registry.paul-steele.com
